server: 
  port: 5223
  
spring: 
  application: 
    name: register-server
#  datasource:  
#    url: jdbc:mysql://localhost:3306/distributed_transaction
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root   
eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:5220/eureka/
tm: 
  manager: 
    url: http://127.0.0.1:8899/tx/manager/