server: 
  port: 5222
  
spring: 
  application: 
    name: wallet-server
  datasource:  
    url: jdbc:mysql://localhost:3306/distributed_tracsaction2
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root   
eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:5220/eureka/
